default_install_hook_types:
  - pre-commit
  - pre-push
# Repos are manually mirrored from github on private repo, to be reachable behind proxy
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.11.2
    hooks:
      - id: ruff-format
        stages: [pre-commit]
      - id: ruff
        args: ["--fix"]
        types_or: [python, pyi] # Removed jupyter
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/uv-pre-commit.git
    rev: 0.6.10
    hooks:
      - id: uv-lock
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        files: stats_loader
        stages: [pre-commit]  # Change to pre-push for performance?
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        # skip integration tests, as these take quite a long time
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [pre-push]
