{
 "title": "GPX Stats",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "\"%Y\",\n\"%Y-%m\",\n\"%Y-%m-%d\""
   }
  ]
 },
 "panels": [
  { "title": "Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distance",
   "type": "stat",
   "description": "max distance observed in an activity in the given time range",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  unixepoch(date) as time,\n  activity,\n  max(distanceMeters)\nFROM summary\nWHERE time >= 1735542968925 / 1000 and time < 1743315368925 / 1000\nGROUP BY activity\n",
     "rawQueryText": "SELECT\n  unixepoch(date) as time,\n  activity,\n  max(distanceMeters)\nFROM summary\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY activity\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "description": "max duration observed in an activity in the given time range",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  unixepoch(date) as time,\n  activity,\n  max(timeSeconds) as duration\nFROM summary\nWHERE time >= 1735542968925 / 1000 and time < 1743315368925 / 1000\nGROUP BY activity\n",
     "rawQueryText": "SELECT\n  unixepoch(date) as time,\n  activity,\n  max(timeSeconds) as duration\nFROM summary\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY activity\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "description": "max average speed  observed in an activity in the given time range",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  unixepoch(date) as time,\n  activity,\n  max(speedMetersPerSecond*3.6)\nFROM summary\nWHERE time >= 1735542968925 / 1000 and time < 1743315368925 / 1000\nGROUP BY activity\n",
     "rawQueryText": "SELECT\n  unixepoch(date) as time,\n  activity,\n  max(speedMetersPerSecond*3.6)\nFROM summary\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY activity\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  speedMetersPerSecond*3.6 as \"avg running speed\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Running\"\nGROUP BY interval",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  speedMetersPerSecond*3.6 as \"avg running speed\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Running\"\nGROUP BY interval",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as interval,\n  activity,\n  speedMetersPerSecond*3.6 as \"avg cycling speed\"\nFROM summary\nWHERE\n  time >= 1735542968925 / 1000 and time < 1743315368925 / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY interval",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  speedMetersPerSecond*3.6 as \"avg cycling speed\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY interval",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  sum(timeSeconds) as \"duration\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\nGROUP BY interval, activity",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  sum(timeSeconds) as \"duration\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\nGROUP BY interval, activity",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  sum(distanceMeters) as distance\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\nGROUP BY interval, activity",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime($interval, date) as interval,\n  activity,\n  sum(distanceMeters) as distance\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\nGROUP BY interval, activity",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "count(.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT unixepoch(date) as time, activity, count(activity) as cnt from summary\nWHERE time >= 1735489295036 / 1000 and time < 1743265295036 / 1000\nGROUP BY activity\n",
     "rawQueryText": "SELECT unixepoch(date) as time, activity, count(activity) as cnt from summary\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY activity\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Activities with average duration (per day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  avg(timeSeconds) as \"avg running duration\"\nFROM summary\nWHERE\n  time >= 1735489295036 / 1000 and time < 1743265295036 / 1000\n  AND activity LIKE \"Running\"\nGROUP BY day",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  avg(timeSeconds) as \"avg running duration\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Running\"\nGROUP BY day",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  avg(timeSeconds) as \"avg cycling duration\"\nFROM summary\nWHERE\n  time >= 1735489295036 / 1000 and time < 1743265295036 / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY day",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  avg(timeSeconds) as \"avg cycling duration\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY day",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  timeSeconds as \"running duration\"\nFROM summary\nWHERE\n  time >= 1735539976168 / 1000 and time < 1743312376168 / 1000\n  AND activity LIKE \"Running\"\nGROUP BY day",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  timeSeconds as \"running duration\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Running\"\nGROUP BY day",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  timeSeconds as \"cycling duration\"\nFROM summary\nWHERE\n  time >= 1735539976168 / 1000 and time < 1743312376168 / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY day",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  timeSeconds as \"cycling duration\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY day",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  distanceMeters as \"running distance\"\nFROM summary\nWHERE\n  time >= 1735539976168 / 1000 and time < 1743312376168 / 1000\n  AND activity LIKE \"Running\"\nGROUP BY day",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  distanceMeters as \"running distance\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Running\"\nGROUP BY day",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  distanceMeters as \"cycling distance\"\nFROM summary\nWHERE\n  time >= 1735539976168 / 1000 and time < 1743312376168 / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY day",
     "rawQueryText": "SELECT \n  unixepoch(date) as time,\n  strftime(\"%Y-%m\", date) as month,\n  strftime(\"%Y-%m-%d\", date) as day,\n  activity,\n  distanceMeters as \"cycling distance\"\nFROM summary\nWHERE\n  time >= $__from / 1000 and time < $__to / 1000\n  AND activity LIKE \"Cycling\"\nGROUP BY day",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "All entries from 'summary'",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT\n  id as id,\n  unixepoch(date) as time,\n  timeSeconds as 'duration',\n  distanceMeters as 'distance',\n  speedMetersPerSecond as 'speed',\n  pace as 'pace (min/km)',\n  activity\nFROM summary\nWHERE time >= 1735539976168 / 1000 and time < 1743312376168 / 1000\nORDER BY time DESC\n",
     "rawQueryText": "SELECT\n  id as id,\n  unixepoch(date) as time,\n  timeSeconds as 'duration',\n  distanceMeters as 'distance',\n  speedMetersPerSecond as 'speed',\n  pace as 'pace (min/km)',\n  activity\nFROM summary\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time DESC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}